name: RayAttributes
version: '${project.version}'
main: cn.earthsky.rayattributes.RayAttributes
api-version: 1.12
softdepend: [PlaceholderAPI]
commands:
  raya:
    description: RayAttributes管理命令
    usage: /raya <give|info|stats|enhance|setlevel|reload>
    permission: rayattributes.admin
