import React, { useState } from 'react';
import EquipmentCreator from './components/EquipmentCreator';
import EnhancementPanel from './components/EnhancementPanel';
import PlayerStats from './components/PlayerStats';
import CombatSimulator from './components/CombatSimulator';
import SetBonusView from './components/SetBonusView';
import AutoGenerateDemo from './components/AutoGenerateDemo';
import EnergySystem from './components/EnergySystem';
import './App.css';

type TabId = 'equip' | 'enhance' | 'player' | 'combat' | 'set' | 'auto' | 'energy';

interface TabDef {
  id: TabId;
  label: string;
  icon: string;
}

const TABS: TabDef[] = [
  { id: 'equip', label: '装备创建', icon: '⚔' },
  { id: 'enhance', label: '强化模拟', icon: '↑' },
  { id: 'player', label: '玩家属性', icon: '👤' },
  { id: 'combat', label: '伤害模拟', icon: '💥' },
  { id: 'auto', label: '自动生成', icon: '⚡' },
  { id: 'set', label: '套装加成', icon: '◆' },
  { id: 'energy', label: '能量系统', icon: '⚡' },
];

export default function App() {
  const [activeTab, setActiveTab] = useState<TabId>('equip');

  const renderContent = () => {
    switch (activeTab) {
      case 'equip': return <EquipmentCreator />;
      case 'enhance': return <EnhancementPanel />;
      case 'player': return <PlayerStats />;
      case 'combat': return <CombatSimulator />;
      case 'auto': return <AutoGenerateDemo />;
      case 'set': return <SetBonusView />;
      case 'energy': return <EnergySystem />;
    }
  };

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>RayAttributes 属性计算模拟器</h1>
        <span className="subtitle">装备生成 · 强化 · 属性计算 · 战斗模拟</span>
      </header>

      <div className="app-body">
        <nav className="sidebar">
          {TABS.map(tab => (
            <button
              key={tab.id}
              className={`nav-btn ${activeTab === tab.id ? 'active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
            >
              <span className="nav-icon">{tab.icon}</span>
              <span className="nav-label">{tab.label}</span>
            </button>
          ))}
        </nav>

        <main className="content">
          {renderContent()}
        </main>
      </div>

      <footer className="app-footer">
        RayAttributes Simulation Tool — 与插件 v2.0 计算逻辑对齐
      </footer>
    </div>
  );
}
