import React, { useState } from 'react';
import { api } from '../api';

const TIER_COLORS: Record<string, string> = { BLUE: '#55f', PURPLE: '#a55', GOLD: '#fa0' };
const SLOTS = ['WEAPON', 'HEAD', 'CHEST', 'LEGS', 'FEET'];
const SLOT_NAMES: Record<string, string> = {
  WEAPON: '武器', HEAD: '头盔', CHEST: '胸甲', LEGS: '护腿', FEET: '靴子',
};
const TIERS = ['BLUE', 'PURPLE', 'GOLD'];

export default function AutoGenerateDemo() {
  const [slot, setSlot] = useState('WEAPON');
  const [tier, setTier] = useState('BLUE');
  const [tagFormat, setTagFormat] = useState('<RayAttributes-Automatic>');
  const [result, setResult] = useState<any>(null);
  const [batchResults, setBatchResults] = useState<any[]>([]);

  const handleGenerate = async () => {
    const res = await api.autoGenerate(slot, tier);
    setResult(res.equipment);
  };

  const handleBatchGenerate = async () => {
    const results: any[] = [];
    for (let i = 0; i < 5; i++) {
      const s = SLOTS[i % SLOTS.length];
      const t = TIERS[Math.floor(Math.random() * TIERS.length)];
      const res = await api.autoGenerate(s, t);
      results.push(res.equipment);
    }
    setBatchResults(results);
  };

  const attrName = (type: string) => {
    const names: Record<string, string> = {
      ATTACK: '攻击力', ATTACK_PERCENT: '攻击力%', HEALTH: '生命',
      HEALTH_PERCENT: '生命%', DEFENSE: '防御', DEFENSE_PERCENT: '防御%',
      CRIT_RATE: '暴击率', CRIT_DAMAGE: '暴击伤害', SKILL_DAMAGE: '技能增伤',
      ENERGY_REGEN: '能量恢复效率', COOLDOWN_REDUCTION: '冷却缩减', DAMAGE_REDUCTION: '伤害减免',
    };
    return names[type] || type;
  };

  const fmtVal = (type: string, val: number) => {
    const isPct = type.includes('PERCENT') || ['CRIT_RATE', 'CRIT_DAMAGE', 'SKILL_DAMAGE',
      'ENERGY_REGEN', 'COOLDOWN_REDUCTION', 'DAMAGE_REDUCTION'].includes(type);
    return isPct ? `${(val * 100).toFixed(1)}%` : val.toFixed(1);
  };

  return (
    <div className="panel">
      <h2>自动生成演示</h2>
      <div className="info-card">
        <div className="info-title">关于 &lt;RayAttributes-Automatic&gt;</div>
        <p>外部插件（如 FantasyWeapon）在物品 lore 中包含此标签时，<br />
          RayAttributes 会自动为该物品生成主词条 + 2 个随机副词条（Lv.1）。</p>
        <p>支持品质限定：<code>&lt;RayAttributes-Automatic:GOLD&gt;</code> 将生成金色品质装备。</p>
      </div>

      <div className="form-row">
        <label>标签格式:</label>
        <div className="tag-display">{tagFormat}</div>
      </div>

      <div className="form-row">
        <label>槽位:</label>
        <select value={slot} onChange={e => setSlot(e.target.value)}>
          {SLOTS.map(s => <option key={s} value={s}>{SLOT_NAMES[s]}</option>)}
        </select>
      </div>

      <div className="form-row">
        <label>品质:</label>
        <div className="tier-group">
          {TIERS.map(t => (
            <button key={t}
              className={`tier-btn ${tier === t ? 'active' : ''}`}
              style={{ borderColor: tier === t ? TIER_COLORS[t] : '#444', color: TIER_COLORS[t] }}
              onClick={() => { setTier(t); setTagFormat(`<RayAttributes-Automatic${t !== 'BLUE' ? ':' + t : ''}>`); }}>
              {t}
            </button>
          ))}
        </div>
      </div>

      <div className="btn-group">
        <button className="btn-primary" onClick={handleGenerate}>单件生成</button>
        <button className="btn-secondary" onClick={handleBatchGenerate}>批量 5 件</button>
      </div>

      {result && (
        <div className="result-card">
          <div className="eq-header">
            <span className="eq-tier" style={{ color: TIER_COLORS[result.tier] }}>{result.tier}</span>
            <span className="eq-slot">{SLOT_NAMES[result.slot]}</span>
            <span className="eq-level">Lv.{result.level}</span>
          </div>
          <div className="stat-section">
            <div className="stat-label">【主词条】</div>
            <div className="stat-row main">
              <span>{attrName(result.mainType)}</span>
              <span className="stat-val">+{fmtVal(result.mainType, result.mainValue)}</span>
            </div>
          </div>
          {Object.keys(result.subStats).length > 0 && (
            <div className="stat-section">
              <div className="stat-label sub-label">【副词条】</div>
              {Object.entries(result.subStats).map(([type, val]) => (
                <div key={type} className="stat-row sub">
                  <span>{attrName(type)}</span>
                  <span className="stat-val">+{fmtVal(type, val as number)}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {batchResults.length > 0 && (
        <div className="batch-results">
          <div className="stat-label">批量生成结果:</div>
          <div className="batch-grid">
            {batchResults.map((eq, i) => (
              <div key={i} className="mini-card">
                <div style={{ color: TIER_COLORS[eq.tier], fontWeight: 'bold' }}>{eq.tier}</div>
                <div>{SLOT_NAMES[eq.slot]}</div>
                <div className="dim">Lv.{eq.level}</div>
                <div className="mini-stat">{attrName(eq.mainType)} +{fmtVal(eq.mainType, eq.mainValue)}</div>
                {Object.entries(eq.subStats).slice(0, 1).map(([t, v]) => (
                  <div key={t} className="mini-stat dim">{attrName(t)} +{fmtVal(t, v as number)}</div>
                ))}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
